version: '3.8'

services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: notes_mysql
    userns_mode: keep-id
    security_opt:
      - label=disable
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes_app
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:Z
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:Z,ro
    networks:
      - notes_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: notes-php:latest
    container_name: notes_php
    userns_mode: keep-id
    security_opt:
      - label=disable
    volumes:
      - ./public:/var/www/html:Z
      - ./api:/var/www/api:Z
      - ./config:/var/www/config:Z
      - ./vendor:/var/www/vendor:Z
    networks:
      - notes_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: notes_app
      DB_USER: notes_user
      DB_PASSWORD: notes_password
      JWT_SECRET: your-secret-key-change-this-in-production
      APP_ENV: production

  nginx:
    image: docker.io/library/nginx:alpine
    container_name: notes_nginx
    userns_mode: keep-id
    security_opt:
      - label=disable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html:Z,ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z,ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:Z,ro
    networks:
      - notes_network
    depends_on:
      - php
    restart: unless-stopped

networks:
  notes_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
