version: '3.8'

services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: notes_mysql_dev
    userns_mode: keep-id
    security_opt:
      - label=disable
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes_app
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql:Z
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:Z,ro
    networks:
      - notes_network_dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: notes-php-dev:latest
    container_name: notes_php_dev
    userns_mode: keep-id
    security_opt:
      - label=disable
    volumes:
      - ./public:/var/www/html:Z
      - ./api:/var/www/api:Z
      - ./config:/var/www/config:Z
      - ./vendor:/var/www/vendor:Z
    networks:
      - notes_network_dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: notes_app
      DB_USER: notes_user
      DB_PASSWORD: notes_password
      JWT_SECRET: dev-secret-key
      APP_ENV: development

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    image: notes-apache-dev:latest
    container_name: notes_apache_dev
    userns_mode: keep-id
    security_opt:
      - label=disable
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html:Z
      - ./api:/var/www/api:Z
      - ./config:/var/www/config:Z
      - ./vendor:/var/www/vendor:Z
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:Z,ro
    networks:
      - notes_network_dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: notes_app
      DB_USER: notes_user
      DB_PASSWORD: notes_password
      JWT_SECRET: dev-secret-key
      APP_ENV: development
    restart: unless-stopped

networks:
  notes_network_dev:
    driver: bridge

volumes:
  mysql_data_dev:
    driver: local
